name: 📦 Build & Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read      # for checkout
  pages: write        # for Pages deployment
  id-token: write     # for Actions permissions

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo (with submodules)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # 2. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v4
        with:
          hugo-version: 'latest'
          extended: true

      # 3. Build the site
      - name: Build
        run: hugo --minify

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
